# Generated by Django 5.0.1 on 2024-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Name')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('image', models.ImageField(blank=True, upload_to='subX/files/images', verbose_name='Image')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
